### ISSUE TITLE
Access Violation in SSE2 function with C++ Builder

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#385]
When I compile GR32 without SSE2 support (with `{$DEFINE OMIT_SSE2}` enabled) everything seems to be working fine. 
When I add SSE2 support it starts to throwing access violation exceptions. In my case in the `function CombineMem_SSE41_Kadaif()` at line:
```
PADDD     XMM2, DQWORD PTR [SSE_003FFF7F_ALIGNED] // XMM2 <- ((ColorX - ColorY) * Weight * $8081) + Bias
```
Exceptions are thrown in both, 32-bit and 64-bit, versions of the code.
I'm using the latest version of C++ Builder 13 Florence with October Patch.

I would appreciate any help from anyone in resolving this issue.

_Originally posted by @tulach in https://github.com/graphics32/graphics32/discussions/346#discussioncomment-14972910_

**Comment by andersmelander** [comment]
@tulach Please create and attach a minimal reproducible example.

**Comment by tulach** [comment]
Hello,
I was using an old GR32 in my projects. So first I tried some simple demo I have from the past. When it didn't work, I migrated to C++ Builder some examples (GradLines, Curves, Benchmark). They threw exceptions just like my demo. I tried it for different platforms (32-bit, 64-bit) and it didn't work the same. Then I turned off SSE2 and it started working. The specific example from my first post is from the [(Curves example](https://github.com/graphics32/graphics32/tree/master/Examples/Drawing/Curves).

I tried to figure out why it wasn't working. When I looked at the compiled code, I found that the line in question was different in the disassembler:

```
GR32.Blend.SSE2.pas.1695: PADDD XMM2, DQWORD PTR [SSE_003FFF7F_ALIGNED] // XMM2 <- ((ColorX - ColorY) * Weight * $8081) + Bias
006F5E41 660FFE1548CB7B00 paddd dqword ptr [$007bcb48],xmm5
```

According to the byte code (660FFE1548CB7B00), it compiles fine and it's just a disassembler bug in C++ Builder.

Then I focused on the definition of SSE_003FFF7F_ALIGNED in the GR32.Types.SIMD file, which uses a trick with the definition of procedures. It occurred to me that the problem might be that it refers to a memory block intended for code and not for data.

So I tried to rewrite GR32.Types.SIMD.pas in a similar way to the way the alpha_ptr and bias_ptr references are created in the GR32_Blend.pas file.

Unfortunately, that didn't help.

Finally, I tried disabling address space randomization (ASLR) in the project settings. That didn't help either. That's why I asked if there was a project available for building GR32 in C++ Builder, to rule out the possibility that I have something set up differently.

**Comment by tulach** [comment]
You can delete USEFORM/USEFORMNS macros. I have other packages with forms where there are no such macros and they are fine.

**Comment by andersmelander** [comment]
> You can delete USEFORM/USEFORMNS macros.

Yes, but I still got the linker errors. I have resolved those now by adding the `Source\Design` folder to the project Library path.

Now I get the same error as you when I try to install the package:
```
Cannot load package 'GR32_CD290.'  It contains unit 'GR32.TEXT.WIN', which is also contained in package 'GR32_CR290'.
```

I think this is because the design-time package is linking statically to the run-time obj-files instead of dynamically to the run-time package.

When I look in the output folder of the run-time package, I have `dcu` and `obj` files that correspond to all the files in the run-time package.

But when I look in the output folder of the design-time package, I have `dcu` and `obj` files that correspond to all the files in **both** packages.

I'm now trying to compare with other 3rd party libraries that contain C++ Builder packages.
Meanwhile I have pushed my files to the [C++Builder_packages](https://github.com/graphics32/graphics32/tree/C%2B%2BBuilder_packages/Source/Packages/CBuilder) branch.

**Comment by andersmelander** [comment]
A quick update although I haven't gotten much further.

I've looked at the `PACKAGEINFO` resource of the design-time package with a resource editor and it revealed something strange:

<img width="344" height="1075" alt="Image" src="https://github.com/user-attachments/assets/aeecf957-9692-4205-959e-6f71e2df866f" />

Notice the `GR32.TEXT.WIN` and `GR32.IMAGEFORMAT.BMP` units; Not only are they both uppercase while everything else is Sentence-cased but they are also the two units that are causing problems at install (because they live in the run-time package).

**Comment by tulach** [comment]
This is a very good observation. I renamed the two units to GR32.ImageFormatsBMP.pas (without the dot) and GR32.Text.Windows.pas and now it can be installed. I think the problem is that when processing resources it takes them as extensions (.bmp, .win) and builds them incorrectly.

However, GradLines still crashes when SSE2 is enabled.

**Comment by andersmelander** [comment]
> I have no idea where it's getting linked in from.

It turns out there was a reference in the project to the Delphi package library: `GR32_R.lib`. With that gone it now crashes on another CombineMem SSE2 implementation. If I disable all the CombineMem SSE2 implementations it works.

<img width="625" height="455" alt="Image" src="https://github.com/user-attachments/assets/4ca80c71-7bff-4674-b250-000b7ce36ecf" />

**Comment by andersmelander** [comment]
Actually, `CombineReg_SSE2` must also be disabled but `CombineMem_SSE41_8081` appears to work.
So it appears to be the use of tables that's the problem, as you observed from the start.

**Comment by tulach** [comment]
I think the problem is how C++ Builder compiles the SSE_003FFF7F_ALIGNED reference when it uses a fake procedure to define the table.

In the disassembler I see [Gr32::Types::SIMD::SSE_003FFF7F_ALIGNED()].
I would expect [Gr32::Types::SIMD::SSE_003FFF7F_ALIGNED] without the brackets.

It would be interesting to compare how the compiled code from Delphi looks against the code that C++ Builder compiles.

I don't like my version with variables because there is an extra instruction instead of direct access.

**Comment by tulach** [comment]
I've never solved this. From what I've searched on the net, they usually solve it with dynamic allocation, where they ensure alignment themselves. That is, what I did, when I used allocation and variables instead of procedures.

And there is `__attribute__ ((vector_size (32)))`, but it only worked for me if I applied it to a local variable on the stack. If I defined it to a global variable, it never had an aligned offset.

```
typedef unsigned char u8x32 __attribute__ ((vector_size (32)));

// This is not aligned. If so, then it's a coincidence.
u8x32 SSE_003FFF7F_ALIGNED = {            
    0x7F, 0xFF, 0x3F, 0x0, // Byte 0..3
    0x7F, 0xFF, 0x3F, 0x0, // Byte 4..7
    0x7F, 0xFF, 0x3F, 0x0, // Byte 8..11
    0x7F, 0xFF, 0x3F, 0x0  // Byte 12..15
};

void myfunction() {

  // This is aligned. In dissasembler you can see how pointer in stack is calculated to be aligned.
  u8x32  SSE_0C080400_ALIGNED = {              
      0x00, 0x04, 0x08, 0x0C, // Byte 0..3
      0x00, 0x04, 0x08, 0x0C, // Byte 4..7
      0x00, 0x04, 0x08, 0x0C, // Byte 8..11
      0x00, 0x04, 0x08, 0x0C  // Byte 12..15
  };

}
```

**Comment by andersmelander** [comment]
Hmm.
I think, instead of trying to find a way to trick the compiler or linker into aligning the data, we should focus on finding out why it works with C++ Builder invoked as a part of RAD Studio, but not with stand-alone C++ Builder.

Since both the compiler and linker are just command line/console applications that are called by the IDE, it should be possible to determine what options and arguments they are using, and what the difference is between the two scenarios. That is, unless it's the Delphi compilation that differs.

Since I'm the one with the RAD Studio installation I guess that falls on me. There goes the weekend :-)

**Comment by tulach** [comment]
There are more ways to define alignment. For example, using `__attribute__ ((aligned (16)))`. But they all lead to the same functionality and I tested them. When I described it, I just chose one of them. It's good to know that someone else confirmed the error in the classic compiler.

Regarding the definition of procedures, I think that in C++ there is no way to define their alignment. It is one thing when Delphi code is generated completely by the Delphi compiler. In the case of C++ Builder, the C++ toolchain is used and Delphi compiles the code into `.obj` files, which are then built using the linker. Therefore, I think there is no room for a solution there. But I would be happy to be wrong :-).

**Comment by andersmelander** [comment]
> It's good to know that someone else confirmed the error in the classic compiler.

The problem is with both the classic and clang 32-bit compiler - but I think I've established that the bug is not in the compiler but in the linker; As you say: The GR32 packages that are _compiled_ with Delphi (except the main stub) and _linked_ with the C++ linker, exhibit the problem.

> Therefore, I think there is no room for a solution there.

I agree; For now, GR32 cannot support 32-bit C++ with SSE enabled.

I will clean up and merge the changes I made earlier to get the packages to install (the bmp and win filenames, missing C++ packages) and then I'll file a bug report on the issues.

**Comment by andersmelander** [comment]
> There is a difference in how a variable is referenced from the assembler when it is declared in the same unit and when it is declared in a different unit (cross-unit). It seems to be handled in Delphi but not in C++ Builder.

I think this is a linker problem, not a compiler problem.

> I moved SSE_003FFF7F_ALIGNED, SSE_0C080400_ALIGNED, alpha_ptr, bias_ptr (with GenAlphaTable and FreeAlphaTable) into GR32.Blend.SSE2.pas and it works.

For `SSE_*_ALIGNED` we could move them, or simply disable their use, as there are alternative implementations that perform almost as well.
However `alpha_ptr` and `bias_ptr` are used outside of the blend units so moving them would not solve the problem everywhere.

> If you wait, I'll test it more, clean it up, and make a fork where I'll publish it so you can test it.

Sure; I'm in no hurry. If you can, then please base your changes on the branch I've already made. This will make it easier for me to track and understand the changes.

**Comment by andersmelander** [comment]
So I finally got time to look at this again and review your changes.

While the changes might solve the problem for you, I simply cannot justify merging them into the main branch for the sake of just a single user - but you probably knew that already.

To summarize, we have encountered the following issues:

1. Missing pure C++ Builder package for use without Delphi personality.
  **Resolved**.
  Can be merged.

2. *.bmp and *.win filenames confuses linker (I'm guessing).
  **Resolved** by renaming the files.
  Can be merged.

3. `SSE_*_ALIGNED` aligned static data.
  **Resolved** by disabling the SSE functions that use them. Not ideal but IMO an acceptable solution.
  Can be merged.

4. `alpha_ptr` and `bias_ptr` static pointers to aligned data.
  **Resolved** by copying the pointer values to local pointer vars. See: fbb75bf4b4386f48c92e0a30e2a94087724a3720
  Can be merged.

5. 64-bit run-time package can't link.
  **Unresolved**.

6. Unit initialization isn't executed with dynamic linking.
  **Unresolved**; I don't believe it should be necessary to manually load and unload the package to get it working.
  More on this later when I have had time to try some things.
